version: "3.10"
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data


  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - db
      - redis
    env_file:
      - .env

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"


volumes:
  db: {}